name: Poke_Img

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip

  # PyTorch with CUDA (GPU support)
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda

  # Other packages
  - albumentations
  - pillow
  - numpy
  - pytest
  - requests
  - matplotlib